ARTICLE_START="<div  class=\"c-view__row\">"
ARTICLE_END="</article>"
LINK_START="<a href=\""
LINK_END="</a>"
LINK_PREPEND="https://www.cisa.gov"
LINK_STRIP_START="<a href=\""
LINK_STRIP_END="\" "
CONTENT_START="<main id=\"main"
CONTENT_END="<div class=\"l-constrain l-page-section--rich-text\">"
PARAGRAPH_START="<h1 class=\"c-page-title__title\">"
PARAGRAPH_END="<div class=\"l-constrain l-page-section--rich-text\">"