ARTICLE_START="<article"
ARTICLE_END="</article>"
LINK_START="<h3 class=\"h5 news__title mb-15\">"
LINK_END="</h3>"
LINK_PREPEND=""
LINK_STRIP_START="<h3 class=\"h5 news__title mb-15\"><a href=\""
LINK_STRIP_END="\" data-page-track="
CONTENT_START="<div class=\"article__content"
CONTENT_END="</article>"
PARAGRAPH_START="<p"
PARAGRAPH_END="</p>"
