name: Chalice Deploy
on:
  push:
    branches:
      - chalice-deploy

jobs:
  Deploy:
    runs-on: self-hosted
    timeout-minutes: 3

    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4

      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME  }}
          password: ${{ secrets.PASSWORD  }}
          key: ${{  secrets.KEY }}
          source: chalice/*
          target: /home/cti/deploy
          timeout: 120s